schema_version = "1.0.0"

id = "uemodel_exporter"
version = "1.0.1"
name = "UEModel Exporter"
tagline = "Add-on for exporting to .uemodel"
maintainer = "HAI | Someone1"
type = "add-on"

tags = ["Import-Export"]

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-2.0-or-later",
]

# platforms = ["windows-x64", "macos-arm64", "linux-x64"]

[permissions]
files = "Export uemodel to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "venv/",
  "blender_vscode_development/",
  "*.uemodel",
]
